FROM python:3.9

WORKDIR /app

# Install system packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 libsm6 libxrender1 libxext6 \
    && rm -rf /var/lib/apt/lists/*

# Copy code and model
COPY . /app/

# Install dependencies
RUN pip install --no-cache-dir torch torchvision pillow

ENTRYPOINT ["python", "inference.py"]
