apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: infra-tools
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.0.19
    helm:
      valuesObject:
        service:
          type: ClusterIP
          port: 3000
        adminUser: admin
        adminPassword: admin123
        persistence:
          enabled: false
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local:80
                access: proxy
                isDefault: true
              - name: PushGateway
                type: prometheus
                url: http://pushgateway-prometheus-pushgateway.monitoring.svc.cluster.local:9091
                access: proxy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
